### ISSUE TITLE
Documentation Checklist

### ISSUE THREAD

**Issue by jolyonb** [mitodl/mitx-grading-library#204]
Here is a checklist of documentation that needs to be written:

# Documentation
- [x] Turn code samples into doctests
- [X] Python 3
- [x] Inline use of a grader
- [x] Attempt-based credit
- [x] Flesh out discussion of plugins
- [x] Course-wide defaults
- [x] `SingleListGrader` - reading from `expect` keyword
- [x] Expanded SingleListGrader expect structure
- [x] ListGrader partial credit off
- [x] Comparers imported using *
- [x] CorrelatedComparer
- [x] `LinearComparer` and `EqualityComparer` (with transform function)
- [x] MatrixEntryComparer
- [x] `FormulaGrader.set_default_comparer`
- [x] Clean up `sample_from` docs to point out that discrete sets can be specified using tuples.
- [x] Matrix sampling
- [x] DiscreteSet can take mixes of numbers and MathArrays
- [x] DependentSampler has access to constants
- [x] Add `min` and `max` to documentation (I think already has floor/ceil)
- [x] Instructor variables
- [x] `IntegralGrader` should be documented
- [x] Expand documentation for `SpecifyDomain` to include `any_length`
- [x] Update javascript documentation

# Course examples
- [x] `LinearComparer` and `EqualityComparer` (with transform function, suggest `np.im`)
- [x] New `StringGrader` features
- [x] Matrix sampling
- [x] Attempt-based credit
- [x] Reading from expect keywords
- [x] Inline use of a grader
- [x] Expanded SingleListGrader expect structure and reading from expect tag
- [x] MatrixEntryComparer
- [x] ListGrader partial credit off
- [x] SetDefaultComparer
- [x] floor/ceil/min/max
- [x] Comparers imported using *
- [x] Go through old examples and polish using new functionality
- [x] Make more integralgrader examples, using different input structures

# Other
- [x] Ensure that all things on this checklist are in the changelog
- [x] Ensure that all things in the changelog are on this checklist ;-)

**Comment by jolyonb** [comment]
@ChristopherChudzicki Figured I'd turn this into a checklist for documentation, rather than have individual issues.

**Comment by jolyonb** [comment]
@ChristopherChudzicki I've now finished writing documentation and examples, and also overhauled all the old content. I'm not expecting you to sift through it all, but if you feel like taking a read... ;-)
